version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql 
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASS: password
    tty: true
    volumes:
      - ./server:/server
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    command: go run main.go
